services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet:v2
    restart: unless-stopped
    environment:
    - SB_USER=admin:admin
    volumes:
      - ./content:/space
    ports:
      - 3000:3000
